version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: moritz
      MYSQL_DATABASE: finance
      MYSQL_PASSWORD: secret
    command:  --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

volumes:
  mysqldata:
